* sudo modprobe snd-aloop
  now hw:Loopback, hw:Loopback,0 and hw:Loopback,1
  appear in the qjackctl device option list
  /proc/asound/card4 is Loopback
  Ah, but aplay -l lists:
card 4: Loopback [Loopback], device 0: Loopback PCM [Loopback PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 4: Loopback [Loopback], device 1: Loopback PCM [Loopback PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
* Okay, added snd-aloop to /etc/modules, let us reboot and test.
  it is loaded
* so hw:Loopback,0,0 is the loopback of hw:Loopback,1,0
  meaning that whoever opens one of them first forces the
  parameters of the Loopback for whoever opens the second.
** so, alsa_in -j iq-input -d hw:Loopback,0,0 -c 2
   connects hw:Loopback,0,0 into jack as iq-input with
   two channels running at the jack sample rate
** then, whoever connects to hw:Loopback,1,0 will see
   a device with two channels accepting samples at
   the jack sample rate.
** now, ideally we would use the iq-input device as
   the samplerate clock for Jack, so Jack opens one
   loopback for iq-input and one for iq-output, then
   does an alsa_in for the microphone and alsa_out for
   the audio monitor, so the audio channels get resampled
   rather than the iq channels.
