* Issues
  This collection has several goals in mind.  Some of them are
  still coming into view, so this description covers what is here and
  what ought to be here.
** Collect useful computations.
** Keep the glue out of sight.
** Update parameters cleanly.
   These computations run in real time on a stream of samples,
   if the parameter updates are glitchy, then the stream will
   sound glitchy.
** The base type for floating point numbers is float
** Each module should supply:
*** a typedef struct { } module_options_t definition.
    This defines the configurable parameters of the module which the
    user may alter.
*** a typedef struct { } module_t definition.
    This defines the storage area required to implement the module
    and to implement any preconfiguration computation staging.  It's
    contents are private to the module.
*** a void module_configure(module_t *p, module_options_t *q) function.
    This performs the parameter changes which were prepared for in the
    preconfigure function.  This function is run inside the
    computation loop and should finish its business as efficiently as
    possible.
*** a void *module_preconfigure(module_t *p, module_options_t *q) function.
    This validates the values of the parameters in *q, does any expensive
    precomputation of state, returns the argument p on success, or a static
    string error message on failure.
    We are outside the computation loop at the time of the call, so we can
    perform expensive computations required by configuration without degrading
    the performance of the computation loop.
*** a void *module_init(module_t *p, module_options_t *q) function.
    This initializes the module in *p, preconfigures its parameters according
    to *q, continues to configure *p, and returns the argument p on success,
    or a or a static string error message on failure. 
*** a void module_process(module_t *p, ...) function
    This function performs the computation using whatever inputs are required
    and the component state stored in *p.
