PKG=pm

LIBDIR=../../lib/faust/$(PKG)

ALL=	$(LIBDIR)/brass.so \
	$(LIBDIR)/clarinet.so \
	$(LIBDIR)/djembe.so \
	$(LIBDIR)/elecGuitar.so \
	$(LIBDIR)/flute.so \
	$(LIBDIR)/guitar.so \
	$(LIBDIR)/ks.so \
	$(LIBDIR)/marimba.so \
	$(LIBDIR)/modularInterpInst.so \
	$(LIBDIR)/nylonGuitar.so \
	$(LIBDIR)/SFFormantModelBP.so \
	$(LIBDIR)/SFFormantModelFofCycle.so \
	$(LIBDIR)/SFFormantModelFofSmooth.so \
	$(LIBDIR)/violin.so

include ../Makefile.subdir
