* Keying envelope
** The dttsp sources
   used a sine shaping
** Doug Smith, On the Occupied Bandwidth of CW Emissions
   hosted at http://www.sm5bsz.com/others/occbw.htm on 2013-01-08
   argues for a raised cosine
** Kevin Schmidt, Spectral Analysis of a CW keying pulse
   (http://fermi.la.asu.edu/w9cf/articles/click/index.html)
   uses a gaussian.
** Oleg Skydan, The T03DSP High Performance Transceiver with DSP IF processing
   (http://t03dsp.skydan.in.ua//CWExciter.htm)
   uses a raised cosine to the fourth power.
** Alex Shovkoplyas, CW Shaping in DSP Software
   QEX, May/June 2006, p. 3-7,
   uses the Blackman-Harris window function as the keying envelope,
   and adjusts the rise time of the envelope to be steeper as the keying speed rises,
   or increases the bandwidth of the signal with keying speed to bw (HZ) = 1.5 key speed (WPM).
   What he does is somewhat more complicated and mysterious than that, but that's my read.
** Ted Williams in TWQRQ
   Implements Hann, and several others, including Hamming, but the others are all multiplied
   by the Hann, they're product windows.
   
* Dit clock vs wpm
| WPM | dit(ms) | dit(Hz) |
|  10 |     120 |     8.3 |
|  20 |      60 |    16.6 |
|  30 |      40 |      25 |
|  40 |      30 |    33.3 |
|  50 |      24 |    41.6 |
|  60 |      20 |      50 |
| 120 |      10 |     100 |


