* Reduce the gain on the softrock output amp
  Using the sdr-widget with a softrock can be improved by reducing the
  gain on the output op amps.
  http://groups.google.com/group/sdr-widget/msg/c46b463dede0fd3b
  Replacing 4k99 with 499 (or matched 470)
  on the RX Ensemble II at R32 and R33.
  on the RXTX Ensemble at R56 and R59.
  In all cases, the feedback resistors from op amp output to inverting
  input.
* Match the BS170's on the TX amp
  The BS170's in the output stage of the RXTX Ensemble are often all
  over the place in their specs, but they're cheap so buy a bunch and
  pick your own matched pairs.
  https://sites.google.com/site/g4zfqradio/matching-bs170-for-softrock
* Using a single wire antenna
With regards to the input circuit on the Ensemble RxII, while I
usually use one of my dipoles and do not need to worry about the BNC
shell/board ground link, occasionally I do use a single wire
antenna. To that end, experimentation showed that putting a permanent
.01 microfarad cap from shell case to board ground (the link option),
brought results similar to using the dipole, given approximately the
same length of antenna and height. I left it in permanently after
testing, it did not effect the dipole usage.

Roland, KB8XI 
* Spurs from the Si570 from a conversation with a SiLabs engineer
  http://groups.yahoo.com/group/softrock40/message/23885
