* Reduce the gain on the softrock output amp
  Using the sdr-widget with a softrock can be improved by reducing the
  gain on the output op amps.
  http://groups.google.com/group/sdr-widget/msg/c46b463dede0fd3b
  Replacing 4k99 with 499 (or matched 470)
  on the RX Ensemble II at R32 and R33.
  on the RXTX Ensemble at R56 and R59.
  In all cases, the feedback resistors from op amp output to inverting
  input.
* Match the BS170's on the TX amp
  The BS170's in the output stage of the RXTX Ensemble are often all
  over the place in their specs, but they're cheap so buy a bunch and
  pick your own matched pairs.
  https://sites.google.com/site/g4zfqradio/matching-bs170-for-softrock
* Using a single wire antenna
With regards to the input circuit on the Ensemble RxII, while I
usually use one of my dipoles and do not need to worry about the BNC
shell/board ground link, occasionally I do use a single wire
antenna. To that end, experimentation showed that putting a permanent
.01 microfarad cap from shell case to board ground (the link option),
brought results similar to using the dipole, given approximately the
same length of antenna and height. I left it in permanently after
testing, it did not effect the dipole usage.

Roland, KB8XI 
* Spurs from the Si570 from a conversation with a SiLabs engineer
  http://groups.yahoo.com/group/softrock40/message/23885
* Running RX Ensemble just from USB power
  Tony experimented with this,
  http://groups.yahoo.com/group/softrock40/message/54144
  run a simple choke between USB power/ground and Softrock analog
  power/ground.
* Modifying Soundblaster X-Fi USB
This has probably been mentioned before but it works so well that it
deserves to be mentioned again. On the web site of IW3AUT is a
document describing how to add two electrolytic bypass caps to the
SB-XFi USB unit model SB-1095. The document contains pictures and and
test results showing the noise floor improvement along with
instructions for adding the caps. The basics are to add 100uf 6.3v
electrolytic across C100 (an existing electrolytic) and 100uf 6.3 volt
across C40. I have done this myslef and measured the improvemnt. It is
every bit as good as he says. I also own an SB1090 which, as it turns
out, has the identical layout for these capacitors and the imrovement
is just as good for this model. There is also a substantial
improvement in the DC "spike" (the bump at the center frequency). To
access the board just peel up the stick on feet and remove the 4
screws underneath. The knob is pressed on so pulling on the top cover
will remove the knob. It requires a small t ip on the iron but I used
plain vanilla electrolytics (not surface mount) and tacked them across
the two caps with as short leads as I could manage reasonably. 

Anthony Casorso canthony15@msn.com
